Update MountsRarity into a single file
sgade/MountsRarity pull request #6
Opened 2023-11-20 16:42 UTC by exochron

This PR moves all data into the main script file. The CI updates that file using sed and some simple regex.
Furthermore the data table is loaded only when needed.

also fixes #5 :)

2023-12-12 18:39 UTC, sgade commented on MountsRarity.lua
> +    data = lazyLoadData()
I very much like the idea of lazy loading the table.

2023-12-12 18:45 UTC, sgade requested changes
Sorry for the long time it took to review this PR. Thanks again for your contribution! I added one comment that you can please incorporate into this PR.

After that, you'd probably wanna rebase your changes on the current state because the `Data.lua` has been updated a few times in the meantime. Please make sure to copy over the current rarities into the new location. Thanks!

2023-12-12 18:45 UTC, sgade commented on scripts/update-rarities.sh
> +sed -i '/Everything after this line/q' MountsRarity.lua
This should use the variable.

```suggestion
sed -i '/Everything after this line/q' $MOUNTS_FILE
```

2023-12-13 20:19 UTC, exochron commented
Done.
After merging you should probably manually run the update action as well, so that the data and version gets updated.

2023-12-13 21:05 UTC, merged

2023-12-13 21:06 UTC, sgade commented
Awesome, merged! Thanks again for your contribution. Looking forward to trying out your addon.